### PR TITLE
readme updated.

### PR DESCRIPTION
**Pull request by jinwoo1996**
ㅋㅋㅋㅋㅋㅋㅋㅋ

### CODE REVIEW

**Review by xorud0524 — COMMENTED** [review]
# It is holly shit

**Comment by jinwoo1996** [comment]
@xorud0524 Thanks!!

**Comment by chkdmin** [comment]
# I hate Jinwoo

**Comment by KimDarren** [comment]
@jinwoo1996 
Thanks for your work, Jinwoo
But, I think this PR is not useful to this project.
So sorry but I need to close this request. 
Thanks again.

**Pull request closed without merging**
